In [ ]:
"""


By starting at the top of the triangle below and moving to adjacent numbers on the row 
below, the maximum total from top to bottom is 23.

3
7 4
2 4 6
8 5 9 3

That is, 3 + 7 + 4 + 9 = 23.

Find the maximum total from top to bottom of the triangle below:

75
95 64
17 47 82
18 35 87 10
20 04 82 47 65
19 01 23 75 03 34
88 02 77 73 07 63 67
99 65 04 28 06 16 70 92
41 41 26 56 83 40 80 70 33
41 48 72 33 47 32 37 16 94 29
53 71 44 65 25 43 91 52 97 51 14
70 11 33 28 77 73 17 78 39 68 17 57
91 71 52 38 17 14 91 43 58 50 27 29 48
63 66 04 68 89 53 67 30 73 16 69 87 40 31
04 62 98 27 23 09 70 98 73 93 38 53 60 04 23

NOTE: As there are only 16384 routes, it is possible to solve this problem by trying every 
route. However, Problem 67, is the same challenge with a triangle containing one-hundred 
rows; it cannot be solved by brute force, and requires a clever method! ;o)

"""

In [44]:
triangle = """3
7 4
2 4 6
8 5 9 3"""

In [45]:
triangle = triangle.split('\n')

In [46]:
import numpy as np

In [47]:
triangle = list(map(lambda x: np.array(x.split(' '), dtype = int), triangle))

In [48]:
triangle

[array([3]), array([7, 4]), array([2, 4, 6]), array([8, 5, 9, 3])]

In [71]:
r = triangle[-1][1:] * triangle[-2]

In [72]:
r

array([10, 36, 18])

In [73]:
l = triangle[-1][:-1] * triangle[-2]

In [74]:
l

array([16, 20, 54])

In [75]:
np.maximum(r, l)

array([16, 36, 54])

In [43]:

for i in range(len(triangle) - 1):
    r = triangle[- i - 1][1:] + triangle[- i - 2]
    l = triangle[- i - 1][:1] + triangle[- i - 2]
    triangle[- i - 2] = np.maximum(r, l)

In [44]:
triangle

[array([23]), array([20, 18]), array([10, 13, 14]), array([8, 5, 9, 3])]

In [53]:
triangle = """75
95 64
17 47 82
18 35 87 10
20 04 82 47 65
19 01 23 75 03 34
88 02 77 73 07 63 67
99 65 04 28 06 16 70 92
41 41 26 56 83 40 80 70 33
41 48 72 33 47 32 37 16 94 29
53 71 44 65 25 43 91 52 97 51 14
70 11 33 28 77 73 17 78 39 68 17 57
91 71 52 38 17 14 91 43 58 50 27 29 48
63 66 04 68 89 53 67 30 73 16 69 87 40 31
04 62 98 27 23 09 70 98 73 93 38 53 60 04 23"""

In [54]:
triangle = triangle.split('\n')

In [55]:
triangle = list(map(lambda x: np.array(x.split(' '), dtype = int), triangle))

In [48]:

for i in range(len(triangle) - 1):
    r = triangle[- i - 1][1:] + triangle[- i - 2]
    l = triangle[- i - 1][:1] + triangle[- i - 2]
    triangle[- i - 2] = np.maximum(r, l)

In [49]:
triangle

[array([1076]),
 array([1001,  970]),
 array([906, 897, 888]),
 array([754, 889, 850, 806]),
 array([736, 724, 854, 763, 796]),
 array([716, 698, 720, 772, 700, 731]),
 array([697, 611, 686, 682, 616, 675, 676]),
 array([609, 543, 497, 567, 484, 534, 612, 570]),
 array([478, 510, 463, 493, 539, 477, 518, 542, 470]),
 array([437, 426, 469, 411, 425, 456, 415, 438, 472, 407]),
 array([378, 396, 369, 397, 353, 368, 424, 377, 422, 376, 339]),
 array([325, 266, 288, 283, 332, 328, 272, 333, 294, 323, 272, 312]),
 array([255, 196, 177, 163, 142, 179, 216, 209, 183, 175, 174, 154, 173]),
 array([125, 164,  31,  91,  98, 123, 165, 103, 166,  54, 122, 147,  44,
         54]),
 array([ 4, 62, 98, 27, 23,  9, 70, 98, 73, 93, 38, 53, 60,  4, 23])]

In [50]:
len(triangle)

15

In [52]:
2**(15 - 1)

16384

In [56]:
res = np.zeros(2**(len(triangle) - 1))
for i in range(2**(len(triangle) - 1)):
    comb = bin(i)[2:].zfill(len(triangle) - 1)[::-1]
    temp = triangle[0][0]
    cur = 0
    for j in range(1, len(triangle)):
        cur += int(comb[j-1])
        temp += triangle[j][cur]
    res[i] = temp
    temp = 0

In [57]:
res

array([794., 663., 694., ..., 761., 792., 724.])

In [58]:
res.max()

1074.0